name: Build macOS wheels

on:
  workflow_call:
    inputs:
      build-commit:
        required: true
        type: string
      artifacts-name:
        required: true
        type: string

env:
  REPO_DIR: Pillow
  TEST_DEPENDS: "pytest pytest-timeout"

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.platform }}
    runs-on: "macos-13"
    strategy:
      fail-fast: false
      matrix:
        python: [
          "pypy3.9-7.3.12",
          "pypy3.10-7.3.12",
          "3.8",
          "3.9",
          "3.10",
          "3.11",
          "3.12",
        ]
        platform: [ "x86_64", "arm64" ]
        exclude:
          - python: "pypy3.9-7.3.12"
            platform: "arm64"
          - python: "pypy3.10-7.3.12"
            platform: "arm64"
    env:
      GH_NAME: ${{ matrix.python }}-${{ matrix.platform }}
      BUILD_COMMIT: ${{ inputs.build-commit }}
      PLAT: ${{ matrix.platform }}
      MB_PYTHON_VERSION: ${{ matrix.python }}
      TRAVIS_OS_NAME: "osx"
    steps:
    # print job name
      - name: Print Job Name
        run: echo ${{ github.job }}
      - name: 2nd try
        run: echo ${{ github.jobs[github.job].name }}
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: System Informaton
        run: |
          echo "PLAT: ${PLAT}"
          echo Platform: $(uname -m)
          sudo ls -ls /usr/local || true
          sudo mkdir -p /usr/local/lib /usr/local/include
      - name: Build Wheel
        run: .github/workflows/build.sh
      - uses: actions/upload-artifact@v4
        with:
        # set name as environment variable GH_NAME
          name: ${{ inputs.artifacts-name }}-linux-${{ env.GH_NAME }}
          path: wheelhouse/*.whl
      # Uncomment to get SSH access for testing
      # - name: Setup tmate session
      #   if: failure()
      #   uses: mxschmitt/action-tmate@v3
